yes|mv autoconf/ /usr/local/Cellar
yes|mv bash-completion/ /usr/local/Cellar
yes|mv berkeley-db/ /usr/local/Cellar
yes|mv berkeley-db@4/ /usr/local/Cellar
yes|mv bison/ /usr/local/Cellar
yes|mv bzip2/ /usr/local/Cellar
yes|mv expat/ /usr/local/Cellar
yes|mv gdbm/ /usr/local/Cellar
yes|mv gnu-tar/ /usr/local/Cellar
yes|mv gpatch/ /usr/local/Cellar
yes|mv libbsd/ /usr/local/Cellar
yes|mv libyaml/ /usr/local/Cellar
yes|mv m4/ /usr/local/Cellar
yes|mv ncurses/ /usr/local/Cellar
yes|mv patchelf/ /usr/local/Cellar
yes|mv perl/ /usr/local/Cellar
yes|mv pkg-config/ /usr/local/Cellar
yes|mv readline/ /usr/local/Cellar
yes|mv sqlite/ /usr/local/Cellar
yes|mv unzip/ /usr/local/Cellar
yes|mv xz/ /usr/local/Cellar
yes|mv zlib/ /usr/local/Cellar
